### ISSUE TITLE
Any example for side bar navigation like netflix?

### ISSUE THREAD

**Issue by Allan-Nava** [rokucommunity/brighterscript-template#2]
I'm trying to develop an OTT platform like netflix, I need the sidebar navigation

**Comment by TwitchBronBron** [comment]
Sorry, this really isn't the place to ask these types of questions. This is a simple template repo for getting started writing Roku apps using [brighterscript](https://github.com/rokucommunity/brighterscript). Feel free to ask this type of question in the [Roku developers slack](https://join.slack.com/t/rokudevelopers/shared_invite/zt-4vw7rg6v-NH46oY7hTktpRIBM_zGvwA)

**Comment by Allan-Nava** [comment]
> Sorry, this really isn't the place to ask these types of questions. This is a simple template repo for getting started writing Roku apps using [brighterscript](https://github.com/rokucommunity/brighterscript). Feel free to ask this type of question in the [Roku developers slack](https://join.slack.com/t/rokudevelopers/shared_invite/zt-4vw7rg6v-NH46oY7hTktpRIBM_zGvwA)

Ok, used the hero grid example but it miss the navigation
